---
- name: Configurar cliente LDAP
  hosts: ldap_clients
  become: yes
  gather_facts: no  # <--- Importante para que Ansible no falle antes de instalar Python

  pre_tasks:
    - name: Verificar si python3.8 está instalado
      stat:
        path: /usr/bin/python3.8
      register: python38_check

    - name: Habilitar repositorio python3.8 si no está instalado
      when: not python38_check.stat.exists
      shell: amazon-linux-extras enable python3.8
      args:
        executable: /bin/bash

    - name: Limpiar metadatos YUM
      when: not python38_check.stat.exists
      command: yum clean metadata

    - name: Instalar python3.8 si no está presente
      when: not python38_check.stat.exists
      yum:
        name: python3.8
        state: present

    - name: Definir intérprete Python 3.8 para el resto del play
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Recoger facts manualmente con Python 3.8
      setup:

  vars_files:
    - vars/ldap-client.yml

  tasks:
    - name: Instalar paquetes necesarios para LDAP (Amazon Linux)
      yum:
        name:
          - nss-pam-ldapd
          - openldap-clients
          - nscd
          - oddjob-mkhomedir
        state: present

    - name: Crear directorio /etc/ldap si no existe
      file:
        path: /etc/ldap
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Configurar /etc/openldap/ldap.conf
      copy:
        dest: /etc/openldap/ldap.conf
        content: |
          URI ldap://{{ ldap_server_ip }}
          BASE {{ ldap_base_dn }}
      notify: Reiniciar servicios LDAP

    - name: Configurar /etc/nslcd.conf
      copy:
        dest: /etc/nslcd.conf
        content: |
          uid nslcd
          gid ldap
          uri ldap://{{ ldap_server_ip }}
          base {{ ldap_base_dn }}
          binddn {{ ldap_root_dn }}
          bindpw {{ ldap_admin_password }}
      notify: Reiniciar servicios LDAP

    - name: Configurar /etc/nsswitch.conf
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^{{ item.key }}:'
        line: '{{ item.key }}:     files ldap'
      loop:
        - { key: 'passwd' }
        - { key: 'group' }
        - { key: 'shadow' }
      notify: Reiniciar servicios LDAP

    - name: Configurar PAM en /etc/pam.d/system-auth (contenido completo)
      copy:
        dest: /etc/pam.d/system-auth
        content: |
          #%PAM-1.0
          # This file is auto-generated.
          # User changes will be destroyed the next time authconfig is run.
          auth        required      pam_env.so
          auth        sufficient    pam_unix.so try_first_pass nullok
          auth        sufficient    pam_ldap.so use_first_pass
          auth        required      pam_deny.so

          account     required      pam_unix.so
          account     sufficient    pam_ldap.so
          account     required      pam_permit.so

          password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
          password    sufficient    pam_unix.so try_first_pass use_authtok nullok sha512 shadow
          password    sufficient    pam_ldap.so use_authtok
          password    required      pam_deny.so

          session     optional      pam_keyinit.so revoke
          session     required      pam_limits.so
          session     required      pam_mkhomedir.so skel=/etc/skel/ umask=0022
          session     optional      pam_systemd.so
          session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
          session     required      pam_unix.so
          session     optional      pam_ldap.so

    - name: Asegurar que el servicio nslcd está activo
      systemd:
        name: nslcd
        state: started
        enabled: yes

    - name: Asegurar que el servicio nscd está activo
      systemd:
        name: nscd
        state: started
        enabled: yes

    - name: Asegurar que oddjobd está activo para crear home
      systemd:
        name: oddjobd
        state: started
        enabled: yes

  handlers:
    - name: Reiniciar servicios LDAP
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - nslcd
        - nscd