---
- name: Configurar LDAP Server (OpenLDAP) en Ubuntu
  hosts: ldap_server
  become: yes

  vars_files:
    - vars/ldap.yml

  tasks:
    - name: Actualizar e instalar paquetes necesarios
      apt:
        name:
          - slapd
          - ldap-utils
        state: present
        update_cache: yes

    - name: Configurar la contraseña del administrador LDAP (slapd)
      debconf:
        name: slapd
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - { question: "slapd/internal/generated_adminpw", value: "{{ ldap_admin_password }}", vtype: "password" }
        - { question: "slapd/password1", value: "{{ ldap_admin_password }}", vtype: "password" }
        - { question: "slapd/password2", value: "{{ ldap_admin_password }}", vtype: "password" }
        - { question: "slapd/domain", value: "{{ ldap_domain_clean }}", vtype: "string" }
        - { question: "slapd/organization", value: "{{ ldap_org }}", vtype: "string" }

    - name: Reiniciar el servicio slapd
      service:
        name: slapd
        state: restarted
        enabled: yes

    - name: Crear estructura base LDAP (OUs)
      shell: |
        ldapadd -x -D "{{ ldap_root_dn }}" -w "{{ ldap_admin_password }}" <<EOF
        dn: {{ ldap_users_ou }}
        objectClass: organizationalUnit
        ou: users

        dn: {{ ldap_groups_ou }}
        objectClass: organizationalUnit
        ou: groups
        EOF
      args:
        executable: /bin/bash
      ignore_errors: yes  # Por si ya existen

    - name: Mostrar estructura LDAP creada
      shell: ldapsearch -x -LLL -b "{{ ldap_base_dn }}"
      register: ldap_structure

    - name: Imprimir estructura LDAP
      debug:
        var: ldap_structure.stdout