---
- name: Configurar LDAP Server (OpenLDAP) en Ubuntu
  hosts: ldap_server
  become: yes

  vars_files:
    - vars/ldap.yml

  tasks:
    - name: Actualizar e instalar paquetes necesarios
      apt:
        name:
          - slapd
          - ldap-utils
          - debconf-utils
        state: present
        update_cache: yes

    - name: Eliminar configuración previa de slapd (si existe)
      shell: |
        systemctl stop slapd || true
        rm -rf /etc/ldap/slapd.d/*
        rm -rf /var/lib/ldap/*
      args:
        executable: /bin/bash

    - name: Preconfigurar slapd con debconf (Contraseña, Dominio, etc.)
      debconf:
        name: slapd
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - { question: "slapd/internal/generated_adminpw", value: "{{ ldap_admin_password }}", vtype: "password" }
        - { question: "slapd/password1", value: "{{ ldap_admin_password }}", vtype: "password" }
        - { question: "slapd/password2", value: "{{ ldap_admin_password }}", vtype: "password" }
        - { question: "slapd/domain", value: "{{ ldap_domain_clean }}", vtype: "string" }
        - { question: "slapd/organization", value: "{{ ldap_org }}", vtype: "string" }
        - { question: "slapd/no_configuration", value: "false", vtype: "boolean" }

    - name: Reconfigurar slapd de forma no interactiva
      shell: |
        echo "slapd slapd/no_configuration boolean false" | debconf-set-selections
        dpkg-reconfigure -f noninteractive slapd
      args:
        executable: /bin/bash


    - name: Reiniciar el servicio slapd (para aplicar configuraciones)
      service:
        name: slapd
        state: restarted
        enabled: yes

    - name: Crear estructura base LDAP (OUs)
      shell: |
        ldapadd -x -D "{{ ldap_root_dn }}" -w "{{ ldap_admin_password }}" <<EOF
        dn: {{ ldap_users_ou }}
        objectClass: organizationalUnit
        ou: users

        dn: {{ ldap_groups_ou }}
        objectClass: organizationalUnit
        ou: groups
        EOF
      args:
        executable: /bin/bash
      ignore_errors: yes  # Por si ya existen

    - name: Copiar datos LDIF al servidor
      copy:
        src: ./datos-ldap/data.ldif
        dest: /tmp/data.ldif

    - name: Aplicar LDIF al servidor LDAP (usuarios, grupos, etc.)
      shell: ldapadd -x -D "{{ ldap_root_dn }}" -w "{{ ldap_admin_password }}" -f /tmp/data.ldif
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Mostrar estructura LDAP creada
      shell: ldapsearch -x -LLL -b "{{ ldap_base_dn }}"
      register: ldap_structure

    - name: Imprimir estructura LDAP
      debug:
        var: ldap_structure.stdout